### PR TITLE
Link to linter rule documentation

### PR DESCRIPTION
**Pull request by j-f1**

### CODE REVIEW

**Comment by j-f1** [comment]
@ricardofbarros Any update on this?

**Comment by j-f1** [comment]
@ricardofbarros Ping?

**Comment by sonicdoe** [comment]
I have [upgraded to Standard Linter v2](https://github.com/ricardofbarros/linter-js-standard/commit/be7b9e97966d846baf2077b8e4eb6728517fac99) so we can take advantage of the new `url` property (see [Linter Message v2](https://github.com/steelbrain/linter/blob/v2.2.0/docs/types/linter-message-v2.md)).

@j-f1 Would you mind updating your branch?

**Comment by sonicdoe** [comment]
Thank you 👍

**Pull request merged**
