### PR TITLE
Fixes #19: Add happiness as a third style option

### LINKED ISSUE #19: Add support for happiness
Would it be difficult to add support for [happiness](https://github.com/JedWatson/happiness). It is also based off of `standard` and the README indicates this module supports it, but that appears to be incorrect.
https://github.com/JedWatson/happiness

### PR DESCRIPTION
**Pull request by developit**
I like this module, but I use tabs and semicolons when writing ES6 - [happiness](https://github.com/JedWatson/happiness) is a fork of `standard`/`semi-standard` that enforces those rules out-of-the-box, so I figured it would make a good addition to this linter.

@ricardofbarros Apologies if I've messed anything up here - this is actually the first time I've tried submitting a PR to a CoffeeScript project :)

_Edit: happiness issue: JedWatson/happiness#3_

### CODE REVIEW

**Comment by ricardofbarros** [comment]
I will review this shortly, but at first glance everything seems fine, I need to start thinking on tests.

**Comment by developit** [comment]
Yup, I was just going to ask if you had a way you normally tested this stuff. I've never hacked on an Atom package before, so I'm not sure if it's like `npm` where I can just swap the files locally or use `link`/`link-local`.

**Comment by ricardofbarros** [comment]
You can do the following:
- `apm link linter-js-standard/ --dev'
- `atom --dev`

I need to read more about the `specs` and how Atom does the unit test and everything, but that is how I test local stuff.

**Comment by developit** [comment]
I was able to confirm it works. On a project with tabs in-use, switching the engine from `standard` to `happiness` brought my error count from ~350 to ~90. Now I just need to fix up my codebase ;)

**Comment by dcousens** [comment]
LGTM thanks @developit :)

**Comment by ricardofbarros** [comment]
Merged :) going to release a patch version and edit the readme. 

Thank you @developit

**Pull request merged**
