### PR TITLE
chore(package): update standard dependency to ^6.0.0

### PR DESCRIPTION
**Pull request by tusharmath**

### CODE REVIEW

**Comment by kunchenguid** [comment]
+1. simple change but helps a lot!

@ricardofbarros

**Comment by timdp** [comment]
+1

**Comment by ryanhiebert** [comment]
:+1: My continuous builds run the latest version of standard for linting, and it started failing (requiring parens around arrow function args). Unfortunately, we're not up-to-date here, so it's not showing me those lint errors in Atom.

**Comment by tonyghita** [comment]
@tusharmath is there a way to pull this change in locally until this gets merged? I'd also like to use `babel-eslint@^5.0.0`

**Comment by tonyghita** [comment]
I was able to use the latest dependencies by just updating the dependencies at `~/.atom/packages/linter-js-standard/package.json` to the versions I wanted, running `npm install`, and finally restarting atom.

**Comment by jamescmartinez** [comment]
Thanks @tonyghita! This will hold me off for now. :)

**Comment by ricardofbarros** [comment]
Hello guys, @devTristan [PR](https://github.com/ricardofbarros/linter-js-standard/pull/101) fixed this issue. Many thanks for him. 🎉 🎉 

This is fix is already published as `3.3.0`.

Thanks.

**Pull request closed without merging**
